/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xdpnvrcsxlcqoqbfyvhy"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkcG52cmNzeGxjcW9xYmZ5dmh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI0MTQ2NzEsImV4cCI6MjA5Nzk5MDY3MX0.dL3qs-1SZ8QjXoq1Gl3xTjN6_wBUcZ18DXG8M-_O6RU"